project_id = "jbstpivfmfxmzxkeoiwh"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.expire-listings]
verify_jwt = false

[functions.track-click]
verify_jwt = false